config/routes.rb
Blog1::Application.routes.draw do

  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout', confirmation: 'verification', unlock: 'unblock', registration: 'account', sign_up: 'new' }

  resources :users, only: [:show]

    root 'posts#index'

      get 'admin' => 'posts#admin'

      get 'new' => 'posts#new', as: :new_post
      get ':slug' => 'posts#show', as: :post
      get ':slug/edit' => 'posts#edit', as: :edit_post
      patch ':slug' => 'posts#update'
      put ':slug' => 'posts#update'
      delete ':slug' => 'posts#destroy'

      resources :posts, only: [:create]

      

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true
	validates :slug, uniqueness: true
	validates :user_id, presence: true
	
	acts_as_url :title, url_attribute: :slug

	belongs_to :user

	def to_param
		slug
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login

  validates :name, presence: true
  validates :username, presence: true, uniqueness: { case_sensitive: false }

  has_many :posts, dependent: :destroy

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	admin_path
	end

	protected

  	def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :password, :remember_me) }
  	  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :username, :password) }
  	  devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :username, :password, :password_confirmation, :current_password) }
  	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorised?, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.where(draft: false).order('updated_at DESC')
  end

  def admin
    @post = Post.new
    @drafts = current_user.posts.where(draft: true)
    @published = current_user.posts.where(draft: false)
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render action: 'edit' }
      end
      format.js
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to :admin }
      format.js
    end
  end

    private
      def set_post
        @post = Post.find_by_slug(params[:slug])
      end

      def authorised?
        unless @post.user == current_user
          redirect_to root_path, notice: "Not authorised to edit this post."
        end
      end

      def post_params
        params.require(:post).permit(:title, :slug, :content, :draft)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts.where(draft: false)
  end
end

app/helpers/application_helper.rb
require 'kramdown'

module ApplicationHelper
	def markdown(text)
		Kramdown::Document.new(text).to_html.html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
	<nav>
		<ul>
			<li><%= link_to "Blog1", root_path, data: { keybinding: 'h' } %></li>
			<% if user_signed_in? %>
				<li><%= link_to "Admin", admin_path, data: { keybinding: 'a' } %></li>
				<li><%= link_to "New", new_post_path, data: { keybinding: 'n' } %></li>
		</ul>
	</nav>
	<ul class="profile">
		<li><%= link_to "Profile", 'javascript:void(0)' %>
			<ul class="profile_links">
				<li><%= link_to "View Profile", user_path(current_user), data: { keybinding: 'p' } %></li>
				<li><%= link_to "Edit Account", edit_user_registration_path %></li>
				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
			</ul>
		</li>
	</ul>
	<% else %>
</nav>
	<ul class="login">
		<li><%= link_to 'Login', new_user_session_path %> </li>
		<li><%= link_to 'Sign Up', new_user_registration_path %></li>
	</ul>
	<% end %>	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//use.typekit.com/glv8hpo.js"></script>
	<script>try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert") %>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
	<h1><%= f.input :title, label: false, placeholder: "Title here...", autofocus: true %></h1>
	<%= f.input :content, label: false, placeholder: "Write post here..." %>
	<%= image_tag("markdown.png", alt: "Markdown", class: "markdown") %>

	<div class="controls">
    <%= f.collection_radio_buttons :draft, [[true, "&nbsp;".html_safe], [false, "&nbsp;".html_safe]], :first, :last %>
    <%= f.input :slug, placeholder: "Slug — Leave blank to use title", label: false %>
    <%= f.button :submit, 'Save', class: "submit-btn" %>
		<%= link_to '&#171 Admin'.html_safe, admin_path, class: "btn admin-controls" %>
  </div>
<% end %>

app/views/posts/_li.html.erb
<% if li.user == current_user %>
	<%= div_for li do %>
		<h4>
			<%= link_to li.title, edit_post_path(li) %> |
			<%= link_to 'View', li, class: 'admin-view' %>
			<%= link_to 'Delete', li, method: :delete, remote: true %>
		</h4>
	<% end %>
<% end %>

app/views/posts/_post.html.erb
<article class="post" id="post-<%= @post.id %>">

	<h1><%= @post.title %></h1>
	<h4>
		<span class="name"><%= link_to @post.user.name, user_path(@post.user) %></span>
		<span class="date"><%= @post.updated_at.strftime('%d %B %Y') %></span>
		<% if @post.user == current_user %>
			<span><%= link_to "Edit this post?", edit_post_path(@post), class: "edit-post" %></span>
			<span><%= link_to "Delete this post?", @post, method: :delete, data: { confirm: "Are you sure?" }, class: "delete-post" %></span>
		<% end %>
	</h4>
	
	<%= markdown(@post.content) unless @post.content.nil? %>

</article>

app/views/posts/_posts.html.erb
<section class="posts">
  <% @posts.each do |post| %>
    <article class="post" id="post-<%= post.id %>">
  
      <h1><%= link_to post.title, post %></h1>
      <h4>
        <span class="name"><%= link_to post.user.name, user_path(post.user) %></span>
        <span class="date"><%= post.updated_at.strftime('%d %B %Y') %></span>
      </h4>
    
      <%= truncate(markdown(post.content), length: 500, separator: ' ', omission: ' ... ', escape: false) {   link_to "Continue Reading &#187".html_safe, post, class: "continue" } %>
    </article>
  <% end %>
</section>

app/views/posts/admin.html.erb
<section class="admin">
	<%= simple_form_for(@post, remote: true) do |f| %>
    <%= f.input :title, placeholder: "Start typing an idea here...", label: false %>
    <%= f.button :submit, 'Save' %>
	<% end %>

	<div class="posts">
		<h2>Ideas</h2>
		<% if @drafts.empty? %>
			No ideas?
		<% else %>
			<div id="ideas">
				<%= render partial: 'li', collection: @drafts %>
			</div>
		<% end %>
	</div>
	
	<hr>
	
	<div class="posts">
		<h2>Published</h2>
		<% if @published.empty? %>
			Write something!
		<% else %>
			<%= render partial: 'li', collection: @published %>
		<% end %>
	</div>
</section>

app/views/posts/create.js.erb
<% if @post.new_record? %>
	$('input#post_title').effect('highlight', { color: 'red' });
<% else %>
	$('#ideas').append("<%= escape_javascript(render @post) %>");
	$('#<%= dom_id(@post) %>').effect('highlight');
	e.preventDefault();
<% end %>

app/views/posts/destroy.js.erb
$('#<%= dom_id(@post) %>').fadeOut();

app/views/posts/edit.html.erb
<section class="form">
	<%= render 'form' %>
</section>

app/views/posts/index.html.erb
<%= render 'posts' %>

app/views/posts/new.html.erb
<section class="form">
	<%= render 'form' %>
</section>

app/views/posts/show.html.erb
<%= render 'post' %>

<% if @post.user == current_user %>
		<%# link_to 'Edit', edit_post_path(@post) %>
		<%# link_to 'Delete', @post, method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>

app/views/users/show.html.erb
<section class="user-view">

	<h1><%= @user.name %></h1>

	<%= render 'posts/posts' %>

</section>